# Generated by Django 4.0 on 2022-12-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idpregunta', models.AutoField(db_column='idPregunta', primary_key=True, serialize=False)),
                ('respuesta', models.PositiveIntegerField()),
                ('pregunta', models.CharField(max_length=300)),
                ('opcion1', models.CharField(blank=True, max_length=100, null=True)),
                ('opcion2', models.CharField(blank=True, max_length=100, null=True)),
                ('opcion3', models.CharField(blank=True, max_length=100, null=True)),
                ('opcion4', models.CharField(blank=True, max_length=100, null=True)),
                ('opcion5', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pregunta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('idtema', models.AutoField(db_column='idTema', primary_key=True, serialize=False)),
                ('tema', models.CharField(db_column='Tema', max_length=45)),
            ],
            options={
                'db_table': 'tema',
                'managed': False,
            },
        ),
    ]
