# Generated by Django 4.0 on 2022-11-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('idTema', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=45)),
            ],
        ),
    ]
