# Generated by Django 4.0 on 2022-11-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_countries_pregunta_puntuacionmax_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tema',
            table='tema',
        ),
    ]
