# Generated by Django 4.0 on 2022-11-25 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idPregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('respuesta', models.SmallIntegerField()),
                ('pregunta', models.CharField(max_length=300)),
                ('opcion1', models.CharField(max_length=45)),
                ('opcion2', models.CharField(max_length=45)),
                ('opcion3', models.CharField(max_length=45)),
                ('opcion4', models.CharField(max_length=45)),
                ('opcion5', models.CharField(max_length=45)),
                ('Tema_idTema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tema')),
            ],
        ),
    ]
