# Generated by Django 4.1.3 on 2022-11-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilaPuntuaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('puntuacion_max', models.IntegerField()),
                ('fecha', models.DateField()),
                ('tema', models.CharField(max_length=45)),
            ],
        ),
    ]
